name: flame_spine
description: Spine support for the Flame game engine. This uses the spine_flutter package and provides wrappers and components to be used inside Flame.
version: 0.3.0+1
publish_to: none
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_spine
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - animations

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.34.0
  flutter:
    sdk: flutter
  spine_flutter:
    git:
      url: https://github.com/ShiroShiroDev/spine-runtimes.git
      ref: 4.3-beta
      path: spine-flutter

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter
  test: any

assets: assets/logo_flame.png
